### ISSUE TITLE
Integrating achievements bonus score functionality with the scoring system (Sept. 8)

### ISSUE THREAD

**Issue by ThatTechedGuy** [UQdeco2800/2021-ext-studio-2#133]
Dispatch an event for the Scoring system team when the achievement card is rendering. The event payload should contain the achievement object.  

The Scoring System UI component will listen to the event and then handle the updation of the score. 

The bonus score UI display will be done by team 7. It is being tracked in #134

**Comment by ThatTechedGuy** [comment]
@Bohan-is-in-the-zone Tagging team 9 to this task. Should I send a PR which listens for bonus score event and updates the ScoringSystem score. Your team can review it and suggest changes / improvements.

**Comment by Bohan-is-in-the-zone** [comment]
I have left a comment under your PR, do you want us to update the score using your existing code or you will do that?

**Comment by ThatTechedGuy** [comment]
@Bohan-is-in-the-zone You guys can update the score using our existing code and push it to our branch!
