### ISSUE TITLE
Scoring System - Suggestions

### ISSUE THREAD

**Issue by ThatTechedGuy** [UQdeco2800/2021-ext-studio-2#146]
**Implementation details :-**
- To create a function called `ScoringSystem.addToScore(int points)` which takes the existing score and adds the `bonus points` to it and updates the score. 
- To update `ScoringSystem.getScore()` to not accept any parameters and return the current score. 

**Documentation needs (optional)**:  Document this method along with usage in the wiki for the studio to see.

**Comment by Bohan-is-in-the-zone** [comment]
Nice multi-team work haha
