### ISSUE TITLE
Score Calculator Logic

### ISSUE THREAD

**Issue by yungseop** [UQdeco2800/2021-ext-studio-2#16]
# **Description**
**Task:** The timer
**Feature:** Scoring System #3 
 
In this task, We will implement a timer that count how many time the player has played since the game starts till the end of the game (i.e. the health bar is zero)
 
## **Example (optional)**
-: When the player has played for 67 seconds. The timer(score board throughout the game) will display 1min 7sec. But in the final score it counts 67 points. "TIME IN SECONDS = SCORES" (Only in the first sprint)
 
# **Dependencies**
Start of the game. This is handled by the given code. 
End of the game. #7 or #5 whoever writes the gameover code. 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 (Aug. 21) FInish the timer (not the UI for the timer)

**Completion Deadline:** Aug. 23

 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
@Bohan-is-in-the-zone (Bohan Xu)
@YiYang200 (Yi Yang)
@Noarrrr (Keyu Bai)
@yungseop (YoungSeob Lee)
@pranavdhoolia (Pranav Dhoolia)

**Comment by Bohan-is-in-the-zone** [comment]
finish
