### ISSUE TITLE
[Suggestion] Scoring System - Using a Service Locator 

### ISSUE THREAD

**Issue by ThatTechedGuy** [UQdeco2800/2021-ext-studio-2#162]
## Suggestion
If Team 9 has time to do this, might be nice to have the Scoring System in the `ServiceLocator`. 
I should be able to write the following snippet to get the current score. 
``` Java 
ServiceLocator.getScoreService().getScore();

ServiceLocator.getScoreService().addToScore(int points);
``` 
## Example:  
This is similar to how we get the in game time.
``` Java 
ServiceLocator.getTimeSource().getTime(); 
```
This will prevent me from importing `ScoringSystemV1` everywhere, because if you guys make `ScoringSystemV2` the porting will be very tedious since I'll have to replace the class everywhere I've used it. I plan to do the same with Achievements in the future. Current setup is verbose and involves importing ScoringSystemV1, making an object and calling the `getScore()` method.

**Comment by Bohan-is-in-the-zone** [comment]
we won't change the name in the rest of this semester. It saves everyone's time :) 
Other group also uses scoringSystemV1. So I think we could just keep the system like this. Sorry about that.

**Comment by ThatTechedGuy** [comment]
Not a problem! @Bohan-is-in-the-zone

**Comment by Bohan-is-in-the-zone** [comment]
Good communication via github anyway haha 😁

**Comment by pranavdhoolia** [comment]
Seems like a good idea. I had been thinking along the same lines since the start of the project.

I only chose not to do this at the time because I couldn’t answer the following questions clearly:

https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Service-Locator#adding-new-services

But I can clearly answer the questions now and think it’d be a great idea to go forward with it.

@henry-burgess @uqtnieva can you please offer your views on the same?

**Comment by Bohan-is-in-the-zone** [comment]
@pranavdhoolia yeah you can implement that if you have time. 😁

**Comment by pranavdhoolia** [comment]
Of course @Bohan-is-in-the-zone, enhancements will only be added once we finish with the current sprint goals. That’s a given.

**Comment by pranavdhoolia** [comment]
@ThatTechedGuy also, as @Bohan-is-in-the-zone stated, **backward compatibility** might be an issue and we need all the other teams using our feature to affirm that they’ll be able to adjust to the new code within a fixed timeframe.

We will maintain the old code only for a fixed time being before deprecating it.
