### ISSUE TITLE
[SonarCloud] Team 7 - Achievements 

### ISSUE THREAD

**Issue by ThatTechedGuy** [UQdeco2800/2021-ext-studio-2#170]
# Description 
**Features:** #127 #126)
Fix SonarCloud Achievements System related problems.

# **Dependencies**
Depends on the working of sonarcloud's integration with the current game.
 
 
# **Milestones**
- [x] `ForestGameArea.java`: Rename `backgroundMusic` usages to `BACKGROUND_MUSIC` - [Link](https://sonarcloud.io/project/issues?id=UQdeco2800_2021-ext-studio-2&issues=AXsAK9UmFn46uFtzuxrV&open=AXsAK9UmFn46uFtzuxrV)

**Completion Deadline:** Currently in hiatus due to sonarcloud not working till 13/9/2021

 
# **Member**
- Akshay Varma (@Butcanudothis )

**Comment by Butcanudothis** [comment]
Closed due to sonarcloud not working till 13/9/2021
