### ISSUE TITLE
[Suggestion] Change AchievementRecords to GameRecords

### ISSUE THREAD

**Issue by pranavdhoolia** [UQdeco2800/2021-ext-studio-2#196]
@ThatTechedGuy just updated the code and saw that **Team 7** has already implemented the functionality to store the game state (including the score) after each game in the local file `achievements.json`

<img width="471" alt="Screenshot 2021-09-12 at 4 55 25 PM" src="https://user-images.githubusercontent.com/24644880/132985753-f79a826d-43f8-40dd-adec-ecdba6bbc15f.png">

One of our **tasks** (#140) is a subset of the abovementioned.
It would be great if you can **expose a method** to provide the **score history** or collaborate with us on the same. 
It would save us a lot of time and redundant code :)

**Comment by ThatTechedGuy** [comment]
Sure, I will expose a method and document the same. Will send a PR. Will take a look at #140 and see what I can do. Thanks for letting me know.
