### ISSUE TITLE
Write monster introduction

### ISSUE THREAD

**Issue by HKeG** [UQdeco2800/2021-ext-studio-2#246]
# **Description**
Add descriptions for different types of obstacles and monsters in the game, including their names, pictures, stories, origins, attack methods, etc., to help users better understand them when playing the game
 
# **Dependencies**
 - Monster Illustrated Book Design Outline (#237 ) 
 
# **Milestones**
- [x] Add description to obstacles (29. 09)
- [x] Add description to monster (29. 09)

 
**Completion Deadline:** 3.10
 
 
# **Documentation**
- [Game Play of Obstacles](../wikis/Obstacles-Gameplay)
- [Design of Obstacles](../wikis/Obstacles)
- [Code Guidelines of Obstacles](Obstacles-Code)
 
# **Members**
- Haoke  (@HKeG ) (Haoke Sheng)

**Comment by lisslulay** [comment]
Related issue #284

**Comment by ThatTechedGuy** [comment]
Please keep @addiii4 @Butcanudothis in the loop. They're working on the game story chapters and the chapter art.
