### ISSUE TITLE
Team 9 Sprint 3 Game Screens bgm design 

### ISSUE THREAD

**Issue by Bohan-is-in-the-zone** [UQdeco2800/2021-ext-studio-2#261]
# Description 
This task we will design bgm for these screens: 
1. GameOver screen 
2. History Score Display screen 
3. Achievement Screen 
4. Main Menu screen 

# Deadline / Milestone

- [x] GameOver screen bgm 25/09/2021
- [x] History Score Display bgm   25/09/2021
- [x] Achievement bgm 27/09/2021
- [x] Main Menu bgm   29/09/2021

**Comment by Bohan-is-in-the-zone** [comment]
@Butcanudothis @ThatTechedGuy Hi, I want to check do you want to design bgm for your achivement screen bgm by yourself or you would like us to design 😀

**Comment by Butcanudothis** [comment]
@Bohan-is-in-the-zone Yes I think that would be great. Please have @pranavdhoolia (or whichever designer is doing) do a rough draft. We can provide feedback for the same and and it can be tweaked accordingly.😃
