### ISSUE TITLE
Team 9 Sprint 3 Main Game Soundtracks Design 

### ISSUE THREAD

**Issue by Bohan-is-in-the-zone** [UQdeco2800/2021-ext-studio-2#262]
# Description 
This task we will design two soundtracks for this main game

# Deadline / Milestone

- [x] The first soundtrack 16/09/2021
- [x] The second soundtrack   21/09/2021

**Comment by pranavdhoolia** [comment]
First Draft: https://soundcloud.com/xcalrez/track1-1/s-HgeFwqCq43I
Please react with a 👍 or  👎 accordingly.

You can also add a brief review if you like.

**Comment by Bohan-is-in-the-zone** [comment]
> First Draft: https://soundcloud.com/xcalrez/track1-1/s-HgeFwqCq43I Please react with a 👍 or 👎 accordingly.
> 
> You can also add a brief review if you like.

Is there only one in that link. We need two I think
