### ISSUE TITLE
Spaceship boss related achievements

### ISSUE THREAD

**Issue by ThatTechedGuy** [UQdeco2800/2021-ext-studio-2#264]
I wanted to create an achievement related to the spaceship boss, say, if the main character successfully avoids the spaceship attacks (missiles?) and survives, across games. I'll need an event to know when Jason has successfully avoided the spaceship attacks (when you resume the frame and Jason starts moving again). Is this possible? So basically, an achievement will be triggered if the player survives against the spaceship boss `X` number of times. 

Team 7 will make and trigger achievements. But we need to know if the player has survived the spaceship attack or not, and trigger an event if he has.

**Comment by lisslulay** [comment]
Hi, I think it is very easy. Refer to the achievements you have combined with other groups, I think I just need to call `AchievementsHelper.getInstance().xxxEvent();`. You can notify me when you finish the corresponding work, and I will call it in the right place : )

**Comment by ThatTechedGuy** [comment]
@lisslulay thanks. Thats what I had in mind. Will do. Let me know if you have any additional ideas.
