### ISSUE TITLE
Team 9 & 7 Achievment Screen bgm design and implementation 

### ISSUE THREAD

**Issue by Bohan-is-in-the-zone** [UQdeco2800/2021-ext-studio-2#267]
# Description 
This task has two part. Team 9 will design several bgm drafts for achievment screen (team 7 feature). They will pick the best one and insert it into the game. 

# Deadline 
2021/9/20

**Comment by ThatTechedGuy** [comment]
FYI, draft 2 was selected based on discord #team-9 channel discussions.
