### ISSUE TITLE
Stones obstacles passing the invisible ceiling

### ISSUE THREAD

**Issue by katrinafu1** [UQdeco2800/2021-ext-studio-2#294]
Team6 has implemented an invisible ceiling that prevents the character to jump out of the map, but the stones obstacles will not be able to pass the ceiling, could team8 please change the falling position of your stones? Thank you!
#22 team8 stones Obstacles

**Comment by lisslulay** [comment]
OK, I will check the code, let us collaborate to solve this problem

**Comment by katrinafu1** [comment]
This is the invisible ceiling implementation you guys can check. 
[spawn invisible ceiling](https://github.com/UQdeco2800/2021-ext-studio-2/commit/3c60a51c9cf0d0c6c50cd4c3726a44f5a3ed5542)
