### ISSUE TITLE
Obstacles Sound effects design 

### ISSUE THREAD

**Issue by Bohan-is-in-the-zone** [UQdeco2800/2021-ext-studio-2#304]
# Description 
This task is designing three sound effects for team 8 - obstacles (by team9).  And then put them into the game(by team 8).

# Milestones 
1. The sound of the spacecraft floating (It's best to play in a loop)                 10/01/2021
2. The sound of a missile explosion (we think it should be less than 1s)          10/01/2021
3. The sound of monster roar (A roar, preferably about one to two seconds) 10/01/2021

**Comment by Bohan-is-in-the-zone** [comment]
The sound effects have been sent into team 8 channel.  :)

**Comment by lisslulay** [comment]
Are you only responsible for providing sound effects or providing functions that can be called?
