### ISSUE TITLE
Providing unlocked achievements data for Attire System (Sept 23)

### ISSUE THREAD

**Issue by ThatTechedGuy** [UQdeco2800/2021-ext-studio-2#307]

**Comment by ThatTechedGuy** [comment]
@kprohith How is Team 1 going about the attire system? Are you changing the attires mid game when an achievement unlocks or will the user be given a choice before the game starts?

**Comment by kprohith** [comment]
> 
> 
> @kprohith How is Team 1 going about the attire system? Are you changing the attires mid game when an achievement unlocks or will the user be given a choice before the game starts?

Creating a menu from which the user can select attires before starting.

**Comment by ThatTechedGuy** [comment]
Okay. So we persist a count of the gold achievements that the user has unlocked and that functionality is already built into the `GameRecords` class that we use to store all the metadata of a game. 
https://github.com/UQdeco2800/2021-ext-studio-2/blob/38732d02555445f3886ea413e1f3d9ebb87aeee2/source/core/src/main/com/deco2800/game/files/GameRecords.java#L199
You can use the number of gold achievements unlocked by the user to unlock attires. We use this same logic to unlock the Game Story Chapters in the AchievementsScreen as well.

**Comment by kprohith** [comment]
> 
> 
> Okay. So we persist a count of the gold achievements that the user has unlocked and that functionality is already built into the `GameRecords` class that we use to store all the metadata of a game.
> 
> https://github.com/UQdeco2800/2021-ext-studio-2/blob/38732d02555445f3886ea413e1f3d9ebb87aeee2/source/core/src/main/com/deco2800/game/files/GameRecords.java#L199
> 
> You can use the number of gold achievements unlocked by the user to unlock attires. We use this same logic to unlock the Game Story Chapters in the AchievementsScreen as well.

Okay, I will check that out. For now I have linked it to the veteran silver and veteran gold achievements as a placeholder.

**Comment by kprohith** [comment]
What is a realistic number that I can use to unlock new attires? Something that is not too hard or time taking, and scales as new achievements are unlocked. @ThatTechedGuy

**Comment by ThatTechedGuy** [comment]
We have 9 - 10 achievements in total, which is a lot. A good idea would be to unlock an attire on every 2 gold achievements (which are unique and have not been unlocked in previous games). `GameRecords.getGoldAchievementsCount();` provides you exactly the value that you need, since the count does not incorporate already unlocked achievements. I guess the logic for this should be relatively straightforward then!

**Comment by kprohith** [comment]
Yup, that works. I'll unlock a new attire for every 2 gold achievements.
