### ISSUE TITLE
New map gold coin generation 

### ISSUE THREAD

**Issue by katrinafu1** [UQdeco2800/2021-ext-studio-2#318]
Hi team1, we have already implemented the new map, could you please add some gold coins to the new map? This is a bonus map without any obstacles. Thank you!
https://github.com/UQdeco2800/2021-ext-studio-2/commit/44b8c49560f714e341ab60ef863fef12f4768110

**Comment by Yonarp** [comment]
@katrinafu1  For sure ill add some coins to the new map

**Comment by katrinafu1** [comment]
(#329) Team6 has already added the coins hhhh
