### ISSUE TITLE
Add final chapter and its associated art.

### ISSUE THREAD

**Issue by Butcanudothis** [UQdeco2800/2021-ext-studio-2#373]
# **Description**
This feature involves adding the final chapter to Jason's adventure which will provide a closure to the story. Along with the final chapter, a chapter art to provide summary of the chapter in pictorial form is added.
 

# **Dependencies**

No dependencies.

 
# **Milestones**
- [x] Final chapter of the story
- [x] Chapter art.

 
**Completion Deadline:** Oct 13
 
# **Documentation**

- [Game story chapters](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Chapters)
- [Google doc draft](https://docs.google.com/document/d/1FwDNmEhNLfvZli3zpIK6qjbi2iRHCM095yEjXAl1YcI/edit)
 
# **Members**
- Aditya Singh Cheema (@addiii4 )
- Akshay Varma (@Butcanudothis )

**Comment by lisslulay** [comment]
hi, the attack feature has been added to the game.
We can assume that Jason finds an assault weapon around the corroded building. He doesn't know what kind of high-tech weapon gun it is, but it only has a limited number of launches. Jason can use this gun to hit mutated plants.
team 8
