### ISSUE TITLE
Music production 

### ISSUE THREAD

**Issue by Bohan-is-in-the-zone** [UQdeco2800/2021-ext-studio-2#385]
# Description 
This task is related to #361. 
I have designed 15 new bgm for this game. Now I think we have enough music for each screen so that user can choose their preference. 

Please have a look at discord music channel. I have sent those music there with their name represents where do they belong. 
Feel free to comment down this ticket 😁 

# Milestone 

- [x] Confirm the bgm for each screen.     11/10/2021
- [x] Commit these new music into the main 11/10/2021

**Comment by Bohan-is-in-the-zone** [comment]
> While committing, please make sure the names follow a consistent format, and are also in camelcase. @Bohan-is-in-the-zone E.g: `bgmSettingsScreen1.mp3`, `bgmSettingsScreen2.mp3`, `bgmAchievementsScreen1.png`, `bgmAchievementsScreen2.png`.
> 
> Overall, great work @Bohan-is-in-the-zone and Team 9!

Yeah sure, I will follow that format

**Comment by ThatTechedGuy** [comment]
> @ThatTechedGuy where do I put these mp3 files? In the `assets/sound` directly or I put them in as a new folder? 

You can create a new folder within `asset/sound` and put it there
