### ISSUE TITLE
Coding the achievement UI (Aug. 28)

### ISSUE THREAD

**Issue by ThatTechedGuy** [UQdeco2800/2021-ext-studio-2#58]
# **Description**
**Task:** Implementing achievements UI
**Feature:** #4 
 
Achievements in the game can be of 3 types (by increasing order of difficulty) :-
- Bronze Trophy
- Silver Trophy
- Gold Trophy

When the game ends, the user will be shown the list of achievements that have been unlocked. Achievement name will be displayed, along with the bonus points that they carry (which will be added to the final score), and the icon (trophy).

## **List of Achievements**
- **Veteran** : Survive for 10 (bronze), 15 (silver) or 20 (gold) minutes
- **Game Breaker**: Survive for 10 (bronze), 15 (silver) or 20 (gold) minutes with full health 
- **Tool Master**: Pickup 10 (bronze), 15 (silver) or 20 (gold) items 
 
# **Dependencies**
- Scoring system and survival seconds #3 
- Infinite loop system: A game end event in order to stop tracking achievements #5 
 
# **Milestones**
- [ ] Code the UI which displays the achievements when the game ends (Aug. 28)
 
**Completion Deadline:** Aug. 29

# **Member**
- Vishal Gupta (s46335906) @ThatTechedGuy 
- Akshay Varma (s4645266) @Butcanudothis

**Comment by Yonarp** [comment]
I have added the itempickedup event trigger #69
