### ISSUE TITLE
Abnormal exit during the game (team 1 will solve it)

### ISSUE THREAD

**Issue by lisslulay** [UQdeco2800/2021-ext-studio-2#91]
The game in main does not run normally, and it will exit unexpectedly in the middle of the game. 

One possible

![image](https://user-images.githubusercontent.com/78423568/132096101-ed1a666a-2226-4db6-9b24-cb4e6c39cbb3.png)

Another possible

![image](https://user-images.githubusercontent.com/78423568/132096109-42351b55-54fb-4645-8ec8-72eb0f9c83bc.png)

**Comment by uqtnieva** [comment]
Have a look here, could be a similar issue: https://deco2800-2021.slack.com/archives/C01R1LVDZGU/p1630561447076000
